### ISSUE TITLE
Documentation ToDo

### ISSUE THREAD

**Issue by choldgraf** [jupyter/repo2docker#78]
- [x] Using debug mode (@choldgraf). See: https://github.com/jupyter/repo2docker/pull/79
- [x] Usage / best-practices for reproducibility (@choldgraf) (https://github.com/jupyterhub/binder/pull/11/files#diff-0ced3dfd44ba156272e6db34a5247462R78 ?)

Long term
---
- [ ] Linter for Dockerfiles (@yuvipanda)

**Comment by choldgraf** [comment]
I think for reproducibility, we could point people to the binder documentation rather than duplicating here. WDYT?

**Comment by choldgraf** [comment]
Short-term things are done so I'm closing this, the linter is covered in BinderHub here: https://github.com/jupyterhub/binderhub/issues/102
